### ISSUE TITLE
[BUG] graph-node error: `Possible reorg detected`

### ISSUE THREAD

**Issue by classicalliu** [nervosnetwork/godwoken#1067]
## **Version**
- Godwoken v1 mainnet

## **Describe the bug**

graph-node pointing to `https://v1.mainnet.godwoken.io/rpc`

```console
Done processing trigger, gas_used: 0, data_source: ERC721, handler: handleTransfer, total_ms: 3169, transaction: 0x1d56…229d, address: 0x2012…95a8, signature: Transfer(indexed address,indexed address,indexed uint256), sgd: 1, subgraph_id: QmQRtVCkr62VV7GqgqdUcAdhoeRy81UfaFcSm1DnBR7Mmv, component: SubgraphInstanceManager
Possible reorg detected, retrying, error: failed to process trigger: block #17463 (0x589c…6d84), transaction 1d567f5bd234f984b9a9651399346c279bd72fc22ac919e19c69a0e005a5229d: Ethereum node returned an error when calling function "supportsInterface" of contract "INationNFT": RPC error: Error { code: InvalidRequest, message: "check balance err: Can't find address for sender: 11377", data: None }
wasm backtrace:
    0: 0x28e7 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall
    1: 0x2a0b - <unknown>!src/types/ERC721/INationNFT/INationNFT#try_supportsInterface
    2: 0x3c84 - <unknown>!src/mappings/utils/ERC721/getOrCreateCollection
    3: 0x48fb - <unknown>!src/mappings/ERC721/handleTransfer
, block_hash: 0x589c39e28f7b8dbdf652f13b59cec2d73d3632ec0c393afe726ee714d5c76d84, block_number: 17463, sgd: 1, subgraph_id: QmQRtVCkr62VV7GqgqdUcAdhoeRy81UfaFcSm1DnBR7Mmv, component: SubgraphInstanceManager
```

**Comment by WhiteR4bbitt** [comment]
Found another few, swapping to another node (https://godwoken.rpc.thirdweb.com) made no difference. (and I do have a local one to the graph node syncing now as well)

```
WARN Trying again after eth_call RPC call for block #200106 (ba1b866e2fdc39d3414f4f5a8fa84c041b6591a751b
4d858cc73d6af4ce366d4) failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: InvalidRequest, message: "check balance err: Can't find address for sender: 11377", data: None }))), sgd: 2, subgraph_id: QmUmKbdDDyHJi36R4eouGyuD6LEKLvHMwZxnPni1GvjaiX, component: SubgraphInstanceManager

INFO Done processing trigger, gas_used: 0, data_source: ERC721, handler: handleTransfer, total_ms: 466,
transaction: 0xa881…eff7, address: 0xeb0f…364e, signature: Transfer(indexed address,indexed address,indexed uint256), sgd: 2, subgraph_id: QmUmKbdDDyHJi36R4eouGyuD6LEKLvHMwZxnPni1GvjaiX, component: SubgraphInstanceManager

INFO Possible reorg detected, retrying, error: failed to process trigger: block #200106 (0xba1b…66d4), t
ransaction a881d040bed2ea6b9deaa107c1f67dc87f734a2ddd824ca0d713f2f47d4feff7: Ethereum node returned an error when calling function "supportsInterface" of contract "INationNFT": RPC error: Error { code: InvalidRequest, message: "check balance err: Can't find address for sender: 11377", data: None }
wasm backtrace:
    0: 0x28e7 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall
    1: 0x2a0b - <unknown>!src/types/ERC721/INationNFT/INationNFT#try_supportsInterface
    2: 0x3c84 - <unknown>!src/mappings/utils/ERC721/getOrCreateCollection
    3: 0x48fb - <unknown>!src/mappings/ERC721/handleTransfer
, block_hash: 0xba1b866e2fdc39d3414f4f5a8fa84c041b6591a751b4d858cc73d6af4ce366d4, block_number: 200106, sgd: 2, subgraph_id: QmUmKbdDDyHJi36R4eouGyuD6LEKLvHMwZxnPni1GvjaiX, component: SubgraphInstanceManager

INFO Scanning blocks [200106, 200106], range_size: 1, sgd: 2, subgraph_id: QmUmKbdDDyHJi36R4eouGyuD6LEKL
vHMwZxnPni1GvjaiX, component: BlockStream

INFO Scanning blocks [200107, 200116], range_size: 10, sgd: 2, subgraph_id: QmUmKbdDDyHJi36R4eouGyuD6LEK
LvHMwZxnPni1GvjaiX, component: BlockStream

INFO Scanning blocks [200117, 200118], range_size: 2, sgd: 2, subgraph_id: QmUmKbdDDyHJi36R4eouGyuD6LEKL
vHMwZxnPni1GvjaiX, component: BlockStream
```

```
INFO Possible reorg detected, retrying, error: failed to process trigger: block #210107 (0x7c70…ab36), t
ransaction 6fb0d09eec8d5b3ae56d98d647766900e11e171f7d26cb5595103ca5f30c1dbd: Ethereum node returned an error when calling function "supportsInterface" of contract "INationNFT": RPC error: Error { code: InvalidRequest, message: "check balance err: Can't find address for sender: 11377", data: None }
wasm backtrace:
    0: 0x28e7 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall
    1: 0x2a0b - <unknown>!src/types/ERC721/INationNFT/INationNFT#try_supportsInterface
    2: 0x3c84 - <unknown>!src/mappings/utils/ERC721/getOrCreateCollection
    3: 0x48fb - <unknown>!src/mappings/ERC721/handleTransfer
, block_hash: 0x7c7076390899807fe05f48d0b48cb5c6db34f8c1f6d0b5fb610f5386df30ab36, block_number: 210107, sgd: 3, subgraph_id: QmTtLBVSLJ8PYMP3daPNwB6BNdA664UzPYYageiC7Ltex4, component: SubgraphInstanceManager
```

**Comment by classicalliu** [comment]
Hello, @WhiteR4bbitt 

Which graph-node version do you use ?
And can you show the subgraph code ?

**Comment by WhiteR4bbitt** [comment]
> Hello, @WhiteR4bbitt
> 
> Which graph-node version do you use ?  
> And can you show the subgraph code ?

`Graph Node version: 0.30.0 (2023-02-22)`

This may have been an isolated issue. Based on the error it is making an assumption that the contract it was checking should have `supportsInterface` available and the mapping is not setup/handling this scenario.

It could still be worth digging, but a wild goose chase as these contracts `erroring` could loosely be `ERC721/1155` contracts deployed on-chain.

Here is the `subgraph.yaml` at the time of question, I have since updated it since learning more about The Graph to better reflect each contract/interface. (but also the `startBlock` is increased now as there is no need to go too far back atm)

And another thing to note is that `NationNFT` on its own DOES NOT have the `supportsInterface` method which I learned among debugging some things. (I didn't write any of the code prior, was just deploying what was there and noticing logs yelling at me along the way)

 ```yaml
specVersion: 0.0.4
description: NFT Nation subgraph set
repository: null
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: NationFactory
    network: gw-mainnet
    source:
      abi: NationFactory
      address: "0x21ef00CA1EaFDD0da6e7a8C1b5a55085e92725Ac"
      startBlock: 453705
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/NationFactory.ts
      entities:
        - Collection
      abis:
        - name: NationFactory
          file: ./abis/NationFactory.json
      eventHandlers:
        - event: SingleCollectionCreated(address,address,string,string,string,uint256,bool)
          handler: handleSingleCollectionCreated
        - event: MultiCollectionCreated(address,address,string,uint256,bool)
          handler: handleMultiCollectionCreated
  - kind: ethereum/contract
    name: NationMarket
    network: gw-mainnet
    source:
      abi: NationMarket
      address: "0x904Bcc39A1629A20104AAe54ef2E62D30ca2af19"
      startBlock: 453708
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/NationMarket.ts
      entities:
        - Item
        - Pair
      abis:
        - name: NationMarket
          file: ./abis/NationMarket.json
      eventHandlers:
        - event: ItemListed((uint256,uint256,address,uint256,address,address,uint256,bool))
          handler: handleItemListed
        - event: ItemDelisted(uint256)
          handler: handleItemDelisted
        - event: ItemUpdated((uint256,uint256,address,uint256,address,address,uint256,bool))
          handler: handleItemUpdated
        - event: ItemPurchased((uint256,uint256,address,uint256,address,address,uint256,bool))
          handler: handleItemPurchased
  - kind: ethereum/contract
    name: NationAuction
    network: gw-mainnet
    source:
      abi: NationAuction
      address: "0x92d5aa4aD01ABDB620FB3E411CF40cC90f47dA94"
      startBlock: 453710
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/NationAuction.ts
      entities:
        - Item
        - Auction
        - Bid
      abis:
        - name: NationAuction
          file: ./abis/NationAuction.json
      eventHandlers:
        - event: AuctionCreated((uint256,address,uint256,uint256,uint256,uint256,uint256,address,address,bool))
          handler: handleAuctionCreated
        - event: AuctionFinalized(uint256,uint256)
          handler: handleAuctionFinalized
        - event: AuctionCanceled(uint256)
          handler: handleAuctionCanceled
        - event: BidCreated(uint256,uint256,(address,uint256,bool))
          handler: handleBidCreated
        - event: BidCanceled(uint256,uint256)
          handler: handleBidCanceled
  - kind: ethereum/contract
    name: ERC721
    network: gw-mainnet
    source:
      abi: ERC721
      startBlock: 1
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/ERC721.ts
      entities:
        - Collection
        - Item
        - ItemOwner
      abis:
        - name: ERC721
          file: ./abis/ERC721.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: INationNFT
          file: ./abis/INationNFT.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
  - kind: ethereum/contract
    name: ERC1155
    network: gw-mainnet
    source:
      abi: ERC1155
      startBlock: 1
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/ERC1155.ts
      entities:
        - Collection
        - Item
        - ItemOwner
      abis:
        - name: ERC1155
          file: ./abis/ERC1155.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: INationNFT
          file: ./abis/INationNFT.json
      eventHandlers:
        - event: TransferSingle(indexed address,indexed address,indexed
            address,uint256,uint256)
          handler: handleTransferSingle
        - event: TransferBatch(indexed address,indexed address,indexed
            address,uint256[],uint256[])
          handler: handleTransferBatch
```
